#!/bin/bash 
astyle \
--style=java \
--indent=spaces=4      \
--break-blocks \
--pad-oper \
--pad-header \
--unpad-paren \
--align-pointer=name \
--align-reference=name  \
--keep-one-line-blocks     \
--keep-one-line-statements \
--convert-tabs \
--mode=c \
--preserve-date \
--quiet \
--lineend=linux \
--suffix=none \
--recursive \
*.cpp *.h *.hpp
